# Generated by Django 3.0.8 on 2021-02-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Name')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('tarefa_ativa', models.CharField(max_length=50, verbose_name='Active Task')),
                ('last_login', models.DateField(auto_now=True, verbose_name='Last Login')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('_pwd', models.CharField(max_length=32, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
